### ISSUE TITLE
  hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by LAIM-LIME** [costiash/whisper-telegram-bot#1]
`023-02-18 11:34:07,233 - apscheduler.scheduler - INFO - Scheduler started
2023-02-18 11:34:07,836 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "C:\Users\F555QA-XO186T\whisper-telegram-bot\main.py", line 42, in start
    dummy_res = predict(DUMMY_AUDIO)
  File "C:\Users\F555QA-XO186T\whisper-telegram-bot\main.py", line 34, in predict
    result = whisper.transcribe(quantized_model, audio_file)
  File "c:\users\f555qa-xo186t\whisper-telegram-bot\whisper\whisper\transcribe.py", line 84, in transcribe
    mel = log_mel_spectrogram(audio)
  File "c:\users\f555qa-xo186t\whisper-telegram-bot\whisper\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "c:\users\f555qa-xo186t\whisper-telegram-bot\whisper\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]`

**Comment by costiash** [comment]
It seems that the error is due the fact you don't ffmpeg installed and configured in you environment variables.
Because you are working on windows I find it hard to help with specific instructions but look online on how to install ffmpeg on windows. Update me if the problem solved.

**Comment by LAIM-LIME** [comment]
Thanks, I really did not consider that, however there's another problem:
`2023-02-18 15:12:59,291 - apscheduler.scheduler - INFO - Scheduler started
2023-02-18 15:29:39,905 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "C:\Users\F555QA-XO186T\whisper-telegram-bot\main.py", line 67, in get_audio
    new_file.download(f"voice_note_{update.effective_user}.ogg")
  File "C:\Users\F555QA-XO186T\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\files\file.py", line 174, in download
    with open(filename, 'wb') as fobj:
OSError: [Errno 22] Invalid argument: "voice_note_{'username': '', 'language_code': 'it', 'id':, 'first_name': '', 'is_bot': False}.ogg"
`

**Comment by costiash** [comment]
Can you please specify the following:
- are you testing it in a local run?
- did you created the connection properly with the telegram bot by supplying the right token id?
- with what kind of file you are getting this error? 
- is the version of python-telegram-bot==13.15?
- do you have writing permissions in the current working directory? because it looks like the program fails to create the audio file locally
